# Generated by Django 4.0.4 on 2022-04-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('exp_data', models.DateTimeField()),
                ('req_price', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('red_line', models.BooleanField())
            ],
        ),
    ]
