version: '3.8'

services:
  backend:
    restart: always
    container_name: back
    
    build:
      context: .
      dockerfile: backend/Dockerfile
    command : "python backend/manage.py runserver localhost:8000"
    ports:  
      - "8000:8000"
    volumes:
      - .:/app/api/
    depends_on:
      - db
      - frontend

  frontend:
    restart: always
    container_name: front
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/app/api/frontend
    command : "npm start"
    ports:
      - "3000:3000"

  db:
    image: docker pull mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_USER: 'hackaton'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always


  

  


