version: '3.8'

services:
  backend:
    restart: always
    container_name: back
    
    build: ./backend/Dockerfile
    command : "python ./app/api/manage.py runserver localhost:8000"
    
    ports:  
      - "8000:8000"
    depends_on: 
      - db
      - frontend

  frontend:
    restart: always
    container_name: front
    
    build: ./frontend/Dockerfile
    command : npm start
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always


  

  


