version: '3.8'

services:
  backend:
    restart: always
    container_name: back
    
    build:
      context: .
      dockerfile: backend/Dockerfile
    command : >
      sh -c "python backend/manage.py makemigrations &&
             python backend/manage.py migrate &&
             python backend/manage.py runserver 0.0.0.0:8000"
    ports:  
      - "8000:8000"
    volumes:
      - .:/app/api/
    depends_on:
      - db
      - frontend

  frontend:
    restart: always
    container_name: front
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/app/api/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command : "npm start"
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    ports:
      - '3307:3307'
    environment:
      MYSQL_DATABASE: 'django_db'
      MYSQL_USER: 'django_db'
      MYSQL_PASSWORD: 'django'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_TCP_PORT: 3307
    restart: always


  

  


